
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/device?characterEncoding=utf-8&useSSL=false
#    106.14.175.3  root   911911
#    118.31.17.203 root ghost
    username: root
    password: cr123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
